# Generated by Django 3.0.2 on 2020-01-20 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('b_chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat_message',
            new_name='ChatMessage',
        ),
    ]
